VISIBILITY:
  visible: true
POSE:
  tick: true
  position:
    type: OFFHAND
    offset:
      x: 0.06
      y: -0.0178
      z: 0.2628
  rotation:
    type: OFFHAND
    aim: false
    quaternion:
      x: 0.0
      y: 0.7071068
      z: 0.0
      w: 0.7071068
  scale: 0.05
RESIZING: {}
