#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Fri Jul 31 09:48:35 MSK 2026
alwaysLogTamperWarnings=true
