template: hud
IDENTITY:
  name: hud
  description: No description
  icon: visor:textures/gui/overlays/missing_icon.png
GENERAL:
  is_hud_layer: true
POSE:
  tick: true
  position:
    type: HMD
    offset:
      x: 0.0
      y: -0.1
      z: -1.2
  rotation:
    type: HMD
    aim: false
    quaternion:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 1.0
  scale: 1.0
SCREEN_REGION:
  region_x: 0
  region_y: 0
  region_width: 1920
  region_height: 1080
RESIZING: {}
