# Applies to all config files that have an associated '.default' file
# When true: All config fields left at their default value will be AUTOMATICALLY UPDATED if the default value changes due to a mod update
# Modpack developers should probably disable this. Regular users should probably keep it enabled.
# default: true
updateDefaultValues = true
# Applies to Flywheel visuals
# When true: Dummy block entity renderers will be registered in addition to Flywheel visuals.
# This can fix issues where visuals become misplaced or are missing
# default: true
registerDummyBERs = true
# Applies to Flywheel visuals with dummy block entity renderers
# When true: All block entities with Flywheel visuals (that are aware of this config) will not skip the vanilla block entity render.
# Probably does nothing except make the game run a tiny bit slower.
# default: false
dontSkipVanillaRender = false
